package it.water.assetcategory.repository;

import it.water.assetcategory.api.AssetCategoryRepository;
import it.water.assetcategory.model.AssetCategory;
import it.water.assetcategory.model.WaterAssetCategoryResource;
import it.water.core.interceptors.annotations.FrameworkComponent;
import it.water.repository.jpa.WaterJpaRepositoryImpl;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * @Generated by Water Generator
 * Repository Class for AssetCategory entity.
 * Handles CRUD operations and custom query methods.
 * Manager logic (add/remove categories) is in AssetCategorySystemServiceImpl.
 */
@FrameworkComponent
public class AssetCategoryRepositoryImpl extends WaterJpaRepositoryImpl<AssetCategory>
        implements AssetCategoryRepository {

    private static final Logger log = LoggerFactory.getLogger(AssetCategoryRepositoryImpl.class);
    private static final String ASSET_CATEGORY_PERSISTENCE_UNIT = "assetCategory-persistence-unit";

    public AssetCategoryRepositoryImpl() {
        super(AssetCategory.class, ASSET_CATEGORY_PERSISTENCE_UNIT);
    }

    /**
     * Find an WaterAssetCategoryResource by its parameters.
     * This is a query method, so it belongs in the Repository.
     */
    @Override
    public WaterAssetCategoryResource findAssetCategoryResource(String resourceName, long resourceId, long categoryId) {
        log.debug("Finding WaterAssetCategoryResource for resource: {} - {} in category: {}",
                resourceName, resourceId, categoryId);
        AssetCategory category = this.find(categoryId);
        if (category != null && category.getResources() != null) {
            return category.getResources().stream()
                    .filter(r -> r.getResourceName().equals(resourceName) && r.getResourceId() == resourceId)
                    .findFirst()
                    .orElse(null);
        }
        return null;
    }
}
