
package it.water.assetcategory.service.rest.spring;

import it.water.assetcategory.service.rest.AssetCategoryRestControllerImpl;
import it.water.core.api.model.*;
import it.water.core.api.repository.*;
import it.water.core.api.repository.query.*;
import it.water.assetcategory.api.*;
import it.water.assetcategory.model.*;
import org.springframework.web.bind.annotation.RestController;


/**
 * @Generated by Water Generator
 * Rest Api Class for AssetCategory entity. It just overrides method invoking super in order to let spring find web methods.
 */
@RestController
public class AssetCategorySpringRestControllerImpl extends AssetCategoryRestControllerImpl implements AssetCategorySpringRestApi {
        @Override
    @SuppressWarnings("java:S1185") //disabling sonar because spring needs to override this method
    public AssetCategory save(AssetCategory entity) {
        return super.save(entity);
    }

    @Override
    @SuppressWarnings("java:S1185") //disabling sonar because spring needs to override this method
    public AssetCategory update(AssetCategory entity) {
        return super.update(entity);
    }

    @Override
    @SuppressWarnings("java:S1185") //disabling sonar because spring needs to override this method
    public void remove(long id) {
        super.remove(id);
    }

    @Override
    @SuppressWarnings("java:S1185") //disabling sonar because spring needs to override this method
    public AssetCategory find(long id) {
        return super.find(id);
    }

    @Override
    @SuppressWarnings("java:S1185") //disabling sonar because spring needs to override this method
    public PaginableResult<AssetCategory> findAll(Integer delta, Integer page, Query filter, QueryOrder order) {
        return super.findAll(delta, page, filter, order);
    }

    @Override
    @SuppressWarnings("java:S1185") //disabling sonar because spring needs to override this method
    public PaginableResult<AssetCategory> findAll() {
        return super.findAll();
    }
    }
