
package it.water.assetcategory.service.rest;

import it.water.assetcategory.api.*;
import it.water.assetcategory.api.rest.*;
import it.water.assetcategory.model.*;

import it.water.core.api.service.BaseEntityApi;
import it.water.service.rest.persistence.BaseEntityRestApi;
import it.water.core.api.service.rest.FrameworkRestController;
import it.water.core.interceptors.annotations.*;


import lombok.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


/**
 * @Generated by Water Generator
 * Rest Api Class for AssetCategory entity.
 *
 */
@FrameworkRestController(referredRestApi = AssetCategoryRestApi.class)
public class AssetCategoryRestControllerImpl extends BaseEntityRestApi<AssetCategory> implements AssetCategoryRestApi {
    @SuppressWarnings("java:S1068") //still mantain the variable even if not used
    private static Logger log = LoggerFactory.getLogger(AssetCategoryRestControllerImpl.class.getName());
    
    @Inject
    @Setter
    private AssetCategoryApi assetCategoryApi;
    @Override
    protected BaseEntityApi<AssetCategory> getEntityService() {
        return assetCategoryApi;
    }
    //All CRUD methods are already exposed by AssetCategoryRestApi interface with JAXRS Annotatiosn
    //if you need to check which methods are exposed please go to it.water.assetcategory.api.rest.AssetCategory

    //ATTENTION: use always AssetCategoryApi in order to ensure the user is requesting operations has the right privileges to do it

}
