package it.water.assetcategory.api;

import it.water.core.api.service.BaseEntitySystemApi;

import it.water.assetcategory.model.AssetCategory;

/**
 * @Generated by Water Generator
 * This interface defines the internally exposed methods for the entity and allows interaction with it bypassing permission system.
 * The main goals of AssetCategorySystemApi is to validate the entity and pass it to the persistence layer.
 */
public interface AssetCategorySystemApi extends BaseEntitySystemApi<AssetCategory> {

}