package it.water.assetcategory.api;

import it.water.assetcategory.model.AssetCategory;
import it.water.assetcategory.model.WaterAssetCategoryResource;
import it.water.core.api.repository.BaseRepository;

/**
 * @Generated by Water Generator
 * Interface component for AssetCategory Repository.
 * It is used for CRUD operations, and to interact with the persistence layer.
 */
public interface AssetCategoryRepository extends BaseRepository<AssetCategory> {

    /**
     * Find an WaterAssetCategoryResource by its parameters
     * @param resourceName the resource class name
     * @param resourceId the resource primary key
     * @param categoryId the category id
     * @return the found WaterAssetCategoryResource or null
     */
    WaterAssetCategoryResource findAssetCategoryResource(String resourceName, long resourceId, long categoryId);
}
