package it.water.assetcategory.api;

import it.water.core.api.service.BaseEntityApi;

import it.water.assetcategory.model.AssetCategory;

/**
 * @Generated by Water Generator
 * This interface defines the externally exposed methods for the entity and allows interaction with it through a permission system.
 *
 */
public interface AssetCategoryApi extends BaseEntityApi<AssetCategory> {

}