package it.water.assetcategory.model;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonView;
import it.water.core.api.entity.shared.SharedEntity;
import it.water.core.api.permission.ProtectedEntity;
import it.water.core.api.service.rest.WaterJsonView;
import it.water.core.permission.action.CrudActions;
import it.water.core.permission.annotations.AccessControl;
import it.water.core.permission.annotations.DefaultRoleAccess;
import it.water.core.validation.annotations.NoMalitiusCode;
import it.water.core.validation.annotations.NotNullOnPersist;
import it.water.repository.jpa.model.AbstractJpaExpandableEntity;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.Size;
import lombok.*;

import java.util.HashSet;
import java.util.Set;


/**
 * @Generated by Water Generator
 * AssetCategory Entity Class.
 * Represents a hierarchical category that can be associated with any entity.
 */
//JPA
@Entity
@Table(uniqueConstraints = @UniqueConstraint(columnNames = {"name", "parent_id"}))
@Access(AccessType.FIELD)
//Lombok
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@RequiredArgsConstructor
@Getter
@Setter(AccessLevel.PROTECTED)
@ToString(exclude = {"parent", "innerAssets", "resources"})
@EqualsAndHashCode(callSuper = true, of = {"name"})
//Actions and default roles access
@AccessControl(availableActions = {CrudActions.SAVE, CrudActions.UPDATE, CrudActions.FIND, CrudActions.FIND_ALL, CrudActions.REMOVE},
        rolesPermissions = {
                //Manager role can do everything
                @DefaultRoleAccess(roleName = AssetCategory.DEFAULT_MANAGER_ROLE, actions = {CrudActions.SAVE, CrudActions.UPDATE, CrudActions.FIND, CrudActions.FIND_ALL, CrudActions.REMOVE}),
                //Viewer has read only access
                @DefaultRoleAccess(roleName = AssetCategory.DEFAULT_VIEWER_ROLE, actions = {CrudActions.FIND, CrudActions.FIND_ALL}),
                //Editor can do anything but remove
                @DefaultRoleAccess(roleName = AssetCategory.DEFAULT_EDITOR_ROLE, actions = {CrudActions.SAVE, CrudActions.UPDATE, CrudActions.FIND, CrudActions.FIND_ALL})
        })
public class AssetCategory extends AbstractJpaExpandableEntity implements ProtectedEntity, SharedEntity {

    public static final String DEFAULT_MANAGER_ROLE = "assetCategoryManager";
    public static final String DEFAULT_VIEWER_ROLE = "assetCategoryViewer";
    public static final String DEFAULT_EDITOR_ROLE = "assetCategoryEditor";

    /**
     * Category name
     */
    @JsonView({WaterJsonView.Extended.class})
    @NotNullOnPersist
    @NotEmpty
    @NoMalitiusCode
    @Size(max = 255)
    @Setter
    @NonNull
    private String name;

    /**
     * Owner user ID (who created the category)
     */
    @JsonView({WaterJsonView.Extended.class})
    @Setter
    @NonNull
    @JsonIgnore
    private Long ownerUserId;

    /**
     * Parent category for hierarchical structure
     */
    @ManyToOne(targetEntity = AssetCategory.class)
    @JoinColumn(name = "parent_id")
    @Setter
    private AssetCategory parent;

    /**
     * Child categories
     */
    @OneToMany(mappedBy = "parent", fetch = FetchType.EAGER, cascade = CascadeType.REMOVE)
    @JsonBackReference
    private Set<AssetCategory> innerAssets = new HashSet<>();

    /**
     * Resources associated with this category
     */
    @JsonIgnore
    @OneToMany(mappedBy = "category", orphanRemoval = true, cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    private Set<AssetCategoryResource> resources = new HashSet<>();

}
