package it.water.assetcategory.model;

import com.fasterxml.jackson.annotation.JsonView;
import it.water.core.api.model.AssetCategoryResource;
import it.water.core.api.permission.ProtectedEntity;
import it.water.core.api.service.rest.WaterJsonView;
import it.water.core.permission.action.CrudActions;
import it.water.core.permission.annotations.AccessControl;
import it.water.core.validation.annotations.NoMalitiusCode;
import it.water.core.validation.annotations.NotNullOnPersist;
import it.water.repository.jpa.model.AbstractJpaExpandableEntity;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotEmpty;
import lombok.*;


/**
 * @Generated by Water Generator
 * WaterAssetCategoryResource Entity Class.
 * Maps the association between any resource (entity) and a category.
 * This allows generic categorization of any entity in the system.
 */
//JPA
@Entity
@Table(name = "asset_category_resource", uniqueConstraints = @UniqueConstraint(columnNames = {"resourceName", "resourceId", "category_id"}))
@Access(AccessType.FIELD)
//Lombok
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@Getter
@Setter(AccessLevel.PROTECTED)
@ToString(exclude = {"category"})
@EqualsAndHashCode(callSuper = true, of = {"resourceName", "resourceId"})
//Actions - internal entity, managed through AssetCategory
@AccessControl(availableActions = {CrudActions.SAVE, CrudActions.UPDATE, CrudActions.FIND, CrudActions.FIND_ALL, CrudActions.REMOVE})
public class WaterAssetCategoryResource extends AbstractJpaExpandableEntity implements ProtectedEntity, AssetCategoryResource {

    /**
     * Resource name - typically the entity class name
     */
    @JsonView({WaterJsonView.Extended.class})
    @NotNullOnPersist
    @NotEmpty
    @NoMalitiusCode
    @NotBlank
    @Setter
    private String resourceName;

    /**
     * Entity primary key
     */
    @JsonView({WaterJsonView.Extended.class})
    @Setter
    private long resourceId;

    /**
     * The associated category
     */
    @ManyToOne(targetEntity = AssetCategory.class)
    @JoinColumn(name = "category_id")
    @Setter
    private AssetCategory category;

    /**
     * Constructor for creating a new WaterAssetCategoryResource
     */
    public WaterAssetCategoryResource(String resourceName, long resourceId, AssetCategory category) {
        this.resourceName = resourceName;
        this.resourceId = resourceId;
        this.category = category;
    }

    /**
     * @return the category id (implements interface method)
     */
    @Override
    public long getCategoryId() {
        return category != null ? category.getId() : 0;
    }
}
