package it.water.assetcategory.service;

import it.water.assetcategory.api.AssetCategoryRepository;
import it.water.assetcategory.api.AssetCategorySystemApi;
import it.water.assetcategory.model.AssetCategory;
import it.water.assetcategory.model.AssetCategoryResource;
import it.water.core.api.asset.AssetCategoryManager;
import it.water.core.api.model.PaginableResult;
import it.water.core.api.registry.filter.ComponentFilterBuilder;
import it.water.core.interceptors.annotations.*;

import it.water.repository.service.BaseEntitySystemServiceImpl;

import lombok.*;

import java.util.ArrayList;
import java.util.List;


/**
 * @Generated by Water Generator
 * System Service Api Class for AssetCategory entity.
 * Implements both AssetCategorySystemApi (entity CRUD) and AssetCategoryManager (cross-module management).
 * This follows the same pattern as UserSystemServiceImpl which implements UserSystemApi and UserManager.
 */
@FrameworkComponent
public class AssetCategorySystemServiceImpl extends BaseEntitySystemServiceImpl<AssetCategory>
        implements AssetCategorySystemApi, AssetCategoryManager {

    @Inject
    @Getter
    @Setter
    private AssetCategoryRepository repository;

    @Inject
    @Setter
    private ComponentFilterBuilder componentFilterBuilder;

    public AssetCategorySystemServiceImpl() {
        super(AssetCategory.class);
    }

    /**
     * Find an AssetCategoryResource by its parameters.
     * Delegates to Repository for the actual query.
     */
    @Override
    public it.water.core.api.model.AssetCategoryResource findAssetCategoryResource(String resourceName, long resourceId, long categoryId) {
        return repository.findAssetCategoryResource(resourceName, resourceId, categoryId);
    }

    /**
     * Add a category to a resource
     */
    @Override
    public void addAssetCategory(String resourceName, long resourceId, long categoryId) {
        getLog().debug("Adding AssetCategory {} to resource: {} - {}", categoryId, resourceName, resourceId);
        AssetCategory category = this.find(categoryId);
        if (category != null) {
            // Check if association already exists
            if (findAssetCategoryResource(resourceName, resourceId, categoryId) == null) {
                AssetCategoryResource acr = new AssetCategoryResource(resourceName, resourceId, category);
                category.getResources().add(acr);
                this.update(category);
            }
        }
    }

    /**
     * Add multiple categories to a resource
     */
    @Override
    public void addAssetCategories(String resourceName, long resourceId, long[] categoriesId) {
        getLog().debug("Adding {} categories to resource: {} - {}", categoriesId.length, resourceName, resourceId);
        for (long categoryId : categoriesId) {
            addAssetCategory(resourceName, resourceId, categoryId);
        }
    }

    /**
     * Find all categories associated with a resource
     */
    @Override
    public long[] findAssetCategories(String resourceName, long resourceId) {
        getLog().debug("Finding categories for resource: {} - {}", resourceName, resourceId);
        List<Long> categoryIds = new ArrayList<>();

        // Get all categories and filter by resource
        PaginableResult<AssetCategory> allCategories = this.findAll(null, -1, -1, null);
        for (AssetCategory category : allCategories.getResults()) {
            if (category.getResources() != null) {
                boolean hasResource = category.getResources().stream()
                        .anyMatch(r -> r.getResourceName().equals(resourceName) && r.getResourceId() == resourceId);
                if (hasResource) {
                    categoryIds.add(category.getId());
                }
            }
        }

        return categoryIds.stream().mapToLong(Long::longValue).toArray();
    }

    /**
     * Remove a category from a resource
     */
    @Override
    public void removeAssetCategory(String resourceName, long resourceId, long categoryId) {
        getLog().debug("Removing AssetCategory {} from resource: {} - {}", categoryId, resourceName, resourceId);
        AssetCategory category = this.find(categoryId);
        if (category != null && category.getResources() != null) {
            // Find and remove the resource from the collection
            AssetCategoryResource toRemove = null;
            for (AssetCategoryResource acr : category.getResources()) {
                if (acr.getResourceName().equals(resourceName) && acr.getResourceId() == resourceId) {
                    toRemove = acr;
                    break;
                }
            }
            if (toRemove != null) {
                category.getResources().remove(toRemove);
                this.update(category);
            }
        }
    }

    /**
     * Remove multiple categories from a resource
     */
    @Override
    public void removeAssetCategories(String resourceName, long resourceId, long[] categoriesId) {
        getLog().debug("Removing {} categories from resource: {} - {}", categoriesId.length, resourceName, resourceId);
        for (long categoryId : categoriesId) {
            removeAssetCategory(resourceName, resourceId, categoryId);
        }
    }
}
