package it.water.assetcategory.service;

import it.water.assetcategory.api.*;
import it.water.assetcategory.model.*;
import it.water.core.api.permission.SecurityContext;
import it.water.core.api.registry.ComponentRegistry;
import it.water.core.interceptors.annotations.*;
import it.water.repository.service.BaseEntityServiceImpl;
import lombok.*;


/**
 * @Generated by Water Generator
 * Service Api Class for AssetCategory entity.
 *
 */
@FrameworkComponent
public class AssetCategoryServiceImpl extends BaseEntityServiceImpl<AssetCategory> implements AssetCategoryApi {

    @Inject
    @Getter
    @Setter
    private AssetCategorySystemApi systemService;

    @Inject
    @Getter
    @Setter
    private ComponentRegistry componentRegistry;

    public AssetCategoryServiceImpl() {
        
        super(AssetCategory.class);
    }

    //use getLog to retrieve Logger instance automatically instantiated for this class
}
